dist: trusty
sudo: required
group: beta

language: node_js
node_js:
  - "8"

services:
  - docker

cache:
  directories:
    - node_modules
env:
  -
  - SOLIDITY_COVERAGE=true
  - SOLC_NIGHTLY=true
matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
    - env: SOLC_NIGHTLY=true
before_script:
  - truffle version
  - docker build -t ocean/plankton-keeper .

install:
  - npm install -g truffle truffle-expect truffle-config ganache-cli web3

before_script:
  - testrpc > testrpc.log &

script:
  - npm install
  - npm test

before_deploy:
  - tar czvf ${TRAVIS_BUILD_DIR}${REPO}-abi-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz ${TRAVIS_BUILD_DIR}/build/contracts/
  - ls -la ${TRAVIS_BUILD_DIR}${REPO}-abi-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
  - tar tzvf ${TRAVIS_BUILD_DIR}${REPO}-abi-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz



#deploy:
#  - provider: npm
#    email: "devops@oceanprotocol.com"
#    api_key: $NPM_AUTH_TOKEN
#    on:
#      tags: true

#  - provider: pypi
#    user: "Your username"
#    password:
#      secure: "Your encrypted password"

#  - provider: releases
#    api_key: $GITHUB_OAUTH_TOKEN
#    file: ${TRAVIS_BUILD_DIR}${REPO}-abi-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
#    skip_cleanup: true
#    on:
#      tags: true

