dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"

services:
  - docker

cache:
  directories:
    - node_modules

env:
  -
  - SOLIDITY_COVERAGE=true
  - SOLC_NIGHTLY=true

matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
    - env: SOLC_NIGHTLY=true

install:
  - npm install
  - npm install -g ganache-cli
  - npm install -g release-it

before_script:
  - truffle version
# - docker build -t ocean/plankton-keeper .
  - ganache-cli > ganache-cli.log &

script:
  - npm test
  - npm run release

notifications:
  email: false

