language: node_js

node_js:
  - "8"

python:
  - "3.6"

services:
  - docker

sudo: yes

cache:
  directories:
    - node_modules

env:
  - DEPLOY_PACKAGE=true
  - SOLIDITY_COVERAGE=true
  - SOLC_NIGHTLY=true

matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
    - env: SOLC_NIGHTLY=true

before_install:
  - sudo apt-get -y install python3-pip
  - pip3 install --user twine six==1.10.0 wheel==0.31.0
  - sudo apt-get install oracle-java8-set-default maven
  - java -version
  - mvn -version
  - export WEB3J_VERSION=3.6.0
  - curl -o web3j-${WEB3J_VERSION}.tar https://github.com/web3j/web3j/releases/download/v${WEB3J_VERSION}/web3j-${WEB3J_VERSION}.tar
  - tar xzf web3j-${WEB3J_VERSION}.tar
  - export PATH="${PWD}/web3j-${WEB3J_VERSION}/bin:${PATH}"
  - web3j version
  - npm install -g npm
  - npm install -g ganache-cli release-it greenkeeper-lockfile

install:
  - npm install

before_script:
  - greenkeeper-lockfile-update
  - ganache-cli > ganache-cli.log &

script:
  - npm run lint
  - npm run test
  - npm run migrate
  - git status
  - git add package-lock.json
  - git diff-index --quiet HEAD || git commit -m "Travis update"

after_script:
  - greenkeeper-lockfile-upload

notifications:
  email: false

deploy:
  - provider: npm
    email: "devops@oceanprotocol.com"
    api_key: ${NPM_TOKEN}
    skip_cleanup: true
    on:
      tags: true
      condition: $DEPLOY_PACKAGE = true

  - provider: script
    script: bash -x ./scripts/deploy_pypi.sh
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      condition: $DEPLOY_PACKAGE = true

#  - provider: releases
#    api_key: ${GITHUB_OAUTH_TOKEN}
#    skip_cleanup: true
#    on:
#      tags: true
