dist: trusty
sudo: required
group: beta

language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules
env:
  -
  - SOLIDITY_COVERAGE=true
  - SOLC_NIGHTLY=true
matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
    - env: SOLC_NIGHTLY=true
before_script:
  - truffle version

before_script:
  - testrpc > testrpc.log &


jobs:
  include:
    - stage: install
      script:
        - npm install -g truffle
        - npm install -g truffle-expect
        - npm install -g truffle-config
        - npm install -g ganache-cli
        - npm install -g web3
        - npm install

    - stage: build
      script:
        - truffle compile

    - stage: test
      script:
        - truffle test

    - stage: package
      script:
        - tar czvf ${TRAVIS_BUILD_DIR}${REPO}-abi-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz ${TRAVIS_BUILD_DIR}/build/contracts/

    - stage: release github
    - stage: release npm

#deploy:
#  provider: releases
#  api_key: $GITHUB_OAUTH_TOKEN
#  file: ${TRAVIS_BUILD_DIR}${REPO}-abi-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
#  skip_cleanup: true
#  on:
#    tags: true

