dist: trusty
sudo: required
group: beta
language: node_js
node_js:
- "8"

services:
- docker

cache:
    directories:
    - node_modules

env:
-
- SOLIDITY_COVERAGE=true
- SOLC_NIGHTLY=true

matrix:
    fast_finish: true
    allow_failures:
    - env: SOLIDITY_COVERAGE=true
    - env: SOLC_NIGHTLY=true

before_install:
    - npm install -g npm
    - npm install -g ganache-cli release-it greenkeeper-lockfile

install:
- npm install -g npm
- npm install
- npm install -g ganache-cli release-it

before_script:
- greenkeeper-lockfile-update
- truffle version
- ganache-cli > ganache-cli.log &

script:
- npm test
- truffle migrate
- git add package-lock.json
- git add artifacts/*
- git commit -m 'Travis Build'
- docker build -t oceanprotocol/keeper-contracts .
- npm run release

after_script: greenkeeper-lockfile-upload

notifications:
    email: false

deploy:
- provider: npm
  email: "devops@oceanprotocol.com"
  api_key: ${NPM_TOKEN}
  skip_cleanup: true
  on:
      tags: true

#  - provider: pypi
#    distributions: sdist bdist_wheel
#    user: leucothia
#    password:
#      secure: XDDyB2Re/4s1x5AsRe3IQeIK9odl0sPhrFqpiD/lWYmzEuty31goFlApZKH/4mCy7qy3edzVGnG46Jlyq4PousvlnaqBQG3wm6ybJqLWGZDrFBTb+7tzvzEa0YvCfQX4dZrRtY84NJvVAvqZoTKGIQSRDyCGkFpiyJpCKUiVIlI/aF1RZslXuivcqgL0YkZwOFyCxQCkfdn4NA3DzGW5GMPoOyIIjEYKNy+7QiBO8L7a/X3nWKHPnrgpd8/bk+mKCH6A5bD9+F7vqFXGZoZ2WxgVp71Ea7xZRTF31TJbvE/atXk/C7xj9NfRwj+5Vz7bpmz+2e2hqQ2D+nRP8qCeQjxoHOnPy/eyaKxm6R/b2Sdm5tWim5A7t+u8I9iwDoYze0d4h9shOIHsSGBiiLutX27moEAIVqduNj9LVlFull23VVBBDyYlRsBQsU1U4nJiscei0ZBash/2yuPUzYqjwQZgnGaoOgiI5joTeHN4huP8XcenRuI5EOfkysCUqtPcmUaT2aT+zRPHwGGQ1blw7CiykNr+niuMRgwZhfKBipvlEnLv79M3VcE7NBj/YxQseIViw4kBV7KKCdvWL+ghV2E9bcEzNsRD4nSk9awAEFecBmSCIiZDIaKTg3FldoYktshwGlj34aQso39110VddjtqRH3X0GyazpMvKvOMZqc=
#    on:
#      tags: true
#      branch: master
#      repo: oceanprotocol/keeper-contracts

#  - provider: releases
#    api_key: ${GITHUB_OAUTH_TOKEN}
#    skip_cleanup: true
#    on:
#      tags: true
