dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"

services:
  - docker

cache:
  directories:
    - node_modules

env:
  - SOLIDITY_COVERAGE=true
  - SOLC_NIGHTLY=true

matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
    - env: SOLC_NIGHTLY=true

install:
  - npm install
  - npm install -g ganache-cli
  - npm install -g release-it

before_script:
  - truffle version
# - docker build -t ocean/plankton-keeper .
  - ganache-cli > ganache-cli.log &

script:
  - npm test

before_deploy:
  - tar czvf ${TRAVIS_BUILD_DIR}${REPO}-abi-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz ${TRAVIS_BUILD_DIR}/build/contracts/
  - ls -la ${TRAVIS_BUILD_DIR}${REPO}-abi-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
  - tar tzvf ${TRAVIS_BUILD_DIR}${REPO}-abi-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz

notifications:
  email: false

deploy:
  - provider: npm
    email: "devops@oceanprotocol.com"
    api_key: ${NPM_AUTH_TOKEN}
    on:
      tags: true
  - provider: pypi
    distributions: sdist bdist_wheel
    user: leucothia
    password:
      secure: XDDyB2Re/4s1x5AsRe3IQeIK9odl0sPhrFqpiD/lWYmzEuty31goFlApZKH/4mCy7qy3edzVGnG46Jlyq4PousvlnaqBQG3wm6ybJqLWGZDrFBTb+7tzvzEa0YvCfQX4dZrRtY84NJvVAvqZoTKGIQSRDyCGkFpiyJpCKUiVIlI/aF1RZslXuivcqgL0YkZwOFyCxQCkfdn4NA3DzGW5GMPoOyIIjEYKNy+7QiBO8L7a/X3nWKHPnrgpd8/bk+mKCH6A5bD9+F7vqFXGZoZ2WxgVp71Ea7xZRTF31TJbvE/atXk/C7xj9NfRwj+5Vz7bpmz+2e2hqQ2D+nRP8qCeQjxoHOnPy/eyaKxm6R/b2Sdm5tWim5A7t+u8I9iwDoYze0d4h9shOIHsSGBiiLutX27moEAIVqduNj9LVlFull23VVBBDyYlRsBQsU1U4nJiscei0ZBash/2yuPUzYqjwQZgnGaoOgiI5joTeHN4huP8XcenRuI5EOfkysCUqtPcmUaT2aT+zRPHwGGQ1blw7CiykNr+niuMRgwZhfKBipvlEnLv79M3VcE7NBj/YxQseIViw4kBV7KKCdvWL+ghV2E9bcEzNsRD4nSk9awAEFecBmSCIiZDIaKTg3FldoYktshwGlj34aQso39110VddjtqRH3X0GyazpMvKvOMZqc=
    on:
      tags: true
      branch: master
      repo: oceanprotocol/keeper-contracts
  - provider: releases
    api_key: ${GITHUB_OAUTH_TOKEN}
    file: ${TRAVIS_BUILD_DIR}${REPO}-abi-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
    skip_cleanup: true
    on:
      tags: true
